config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: 'letter_opener' if Rails.env.development?

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web, at: 'sidekiq', as: :sidekiq
    mount PgHero::Engine, at: 'pghero', as: :pghero
  end

  use_doorkeeper do
    controllers authorizations: 'oauth/authorizations', authorized_applications: 'oauth/authorized_applications'
  end

  get '.well-known/host-meta', to: 'xrd#host_meta', as: :host_meta
  get '.well-known/webfinger', to: 'xrd#webfinger', as: :webfinger

  devise_for :users, path: 'auth', controllers: {
    sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    passwords:          'auth/passwords',
    confirmations:      'auth/confirmations',
  }

  get '/users/:username', to: redirect('/@%{username}'), constraints: { format: :html }

  resources :accounts, path: 'users', only: [:show], param: :username do
    resources :stream_entries, path: 'updates', only: [:show] do
      member do
        get :embed
      end
    end

    get :remote_follow,  to: 'remote_follow#new'
    post :remote_follow, to: 'remote_follow#create'

    member do
      get :followers
      get :following

      post :follow
      post :unfollow
    end
  end

  get '/@:username', to: 'accounts#show', as: :short_account
  get '/@:account_username/:id', to: 'statuses#show', as: :short_account_status

  namespace :settings do
    resource :profile, only: [:show, :update]
    resource :preferences, only: [:show, :update]
    resource :import, only: [:show, :create]

    resource :export, only: [:show] do
      collection do
        get :follows, to: 'exports#download_following_list'
        get :blocks, to: 'exports#download_blocking_list'
      end
    end

    resource :two_factor_auth, only: [:show, :new, :create] do
      member do
        post :disable
      end
    end
  end

  resources :media, only: [:show]
  resources :tags,  only: [:show]

  # Remote follow
  get  :authorize_follow, to: 'authorize_follow#new'
  post :authorize_follow, to: 'authorize_follow#create'

  namespace :admin do
    resources :pubsubhubbub, only: [:index]
    resources :domain_blocks, only: [:index, :new, :create]
    resources :settings, only: [:index, :update]

    resources :reports, only: [:index, :show] do
      member do
        post :resolve
        post :silence
        post :suspend
        post :remove
      end
    end

    resources :accounts, only: [:index, :show] do
      member do
        post :silence
        post :unsilence
        post :suspend
        post :unsuspend
      end
    end
  end

  get '/admin', to: redirect('/admin/settings', status: 302)

  namespace :api do
    # PubSubHubbub outgoing subscriptions
    resources :subscriptions, only: [:show]
    post '/subscriptions/:id', to: 'subscriptions#update'

    # PubSubHubbub incoming subscriptions
    post '/push', to: 'push#update', as: :push

    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    # OEmbed
    get '/oembed', to: 'oembed#show', as: :oembed

    # JSON / REST API
    namespace :v1 do
      resources :statuses, only: [:create, :show, :destroy] do
        member do
          get :context
          get :card
          get :reblogged_by
          get :favourited_by

          post :reblog
          post :unreblog
          post :favourite
          post :unfavourite
        end
      end

      get '/timelines/home',     to: 'timelines#home', as: :home_timeline
      get '/timelines/public',   to: 'timelines#public', as: :public_timeline
      get '/timelines/tag/:id',  to: 'timelines#tag', as: :hashtag_timeline

      get '/search', to: 'search#index', as: :search

      resources :follows,    only: [:create]
      resources :media,      only: [:create]
      resources :apps,       only: [:create]
      resources :blocks,     only: [:index]
      resources :mutes,      only: [:index]
      resources :favourites, only: [:index]
      resources :reports,    only: [:index, :create]

      resource :instance, only: [:show]

      resources :follow_requests, only: [:index] do
        member do
          post :authorize
          post :reject
        end
      end

      resources :notifications, only: [:index, :show] do
        collection do
          post :clear
        end
      end

      resources :accounts, only: [:show] do
        collection do
          get :relationships
          get :verify_credentials
          patch :update_credentials
          get :search
        end

        member do
          get :statuses
          get :followers
          get :following

          post :follow
          post :unfollow
          post :block
          post :unblock
          post :mute
          post :unmute
        end
      end
    end

    namespace :web do
      resource :settings, only: [:update]
    end
  end

  get '/web/(*any)', to: 'home#index', as: :web

  get '/about',      to: 'about#show'
  get '/about/more', to: 'about#more'
  get '/terms',      to: 'about#terms'

  root 'home#index'

  match '*unmatched_route',
    via: :all,
    to: 'application#raise_not_found',
    format: false
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  belongs_to :account
  belongs_to :target_account, class_name: 'Account'
  belongs_to :action_taken_by_account, class_name: 'Account'

  scope :unresolved, -> { where(action_taken: false) }
  scope :resolved,   -> { where(action_taken: true) }
end

app/controllers/admin/reports_controller.rb
# frozen_string_literal: true

class Admin::ReportsController < ApplicationController
  before_action :require_admin!
  before_action :set_report, except: [:index]

  layout 'admin'

  def index
    @reports = Report.includes(:account, :target_account).order('id desc').paginate(page: params[:page], per_page: 40)
    @reports = params[:action_taken].present? ? @reports.resolved : @reports.unresolved
  end

  def show
    @statuses = Status.where(id: @report.status_ids)
  end

  def resolve
    @report.update(action_taken: true, action_taken_by_account_id: current_account.id)
    redirect_to admin_report_path(@report)
  end

  def suspend
    Admin::SuspensionWorker.perform_async(@report.target_account.id)
    Report.unresolved.where(target_account: @report.target_account).update_all(action_taken: true, action_taken_by_account_id: current_account.id)
    redirect_to admin_report_path(@report)
  end

  def silence
    @report.target_account.update(silenced: true)
    Report.unresolved.where(target_account: @report.target_account).update_all(action_taken: true, action_taken_by_account_id: current_account.id)
    redirect_to admin_report_path(@report)
  end

  def remove
    RemovalWorker.perform_async(params[:status_id])
    redirect_to admin_report_path(@report)
  end

  private

  def set_report
    @report = Report.find(params[:id])
  end
end

app/controllers/api/v1/reports_controller.rb
# frozen_string_literal: true

class Api::V1::ReportsController < ApiController
  before_action -> { doorkeeper_authorize! :read }, except: [:create]
  before_action -> { doorkeeper_authorize! :write }, only:  [:create]
  before_action :require_user!

  respond_to :json

  def index
    @reports = Report.where(account: current_account)
  end

  def create
    status_ids = report_params[:status_ids].is_a?(Enumerable) ? report_params[:status_ids] : [report_params[:status_ids]]

    @report = Report.create!(account: current_account,
                             target_account: Account.find(report_params[:account_id]),
                             status_ids: Status.find(status_ids).pluck(:id),
                             comment: report_params[:comment])

    render :show
  end

  private

  def report_params
    params.permit(:account_id, :comment, status_ids: [])
  end
end

app/views/admin/reports/index.html.haml
- content_for :page_title do
  Reports

.filters
  .filter-subset
    %strong Status
    %ul
      %li= filter_link_to 'Unresolved', action_taken: nil
      %li= filter_link_to 'Resolved', action_taken: '1'

= form_tag do

  %table.table
    %thead
      %tr
        %th
        %th ID
        %th Target
        %th Reported by
        %th Comment
        %th
    %tbody
      - @reports.each do |report|
        %tr
          %td= check_box_tag 'select', report.id
          %td= "##{report.id}"
          %td= link_to report.target_account.acct, admin_account_path(report.target_account.id)
          %td= link_to report.account.acct, admin_account_path(report.account.id)
          %td= truncate(report.comment, length: 30, separator: ' ')
          %td= table_link_to 'circle', 'View', admin_report_path(report)

= will_paginate @reports, pagination_options

app/views/admin/reports/show.html.haml
- content_for :page_title do
  = "Report ##{@report.id}"

.report-accounts
  .report-accounts__item
    %strong Reported account:
    = render partial: 'authorize_follow/card', locals: { account: @report.target_account }
  .report-accounts__item
    %strong Reported by:
    = render partial: 'authorize_follow/card', locals: { account: @report.account }

%p
  %strong Comment:
  - if @report.comment.blank?
    None
  - else
    = @report.comment

- unless @statuses.empty?
  %hr/

  - @statuses.each do |status|
    .report-status
      .activity-stream.activity-stream-headless
        .entry= render partial: 'stream_entries/simple_status', locals: { status: status }
      .report-status__actions
        = link_to remove_admin_report_path(@report, status_id: status.id), method: :post, class: 'icon-button', style: 'font-size: 24px; width: 24px; height: 24px', title: 'Delete' do
          = fa_icon 'trash'

- if !@report.action_taken?
  %hr/

  %div{ style: 'overflow: hidden' }
    %div{ style: 'float: right' }
      = link_to 'Silence account', silence_admin_report_path(@report), method: :post, class: 'button'
      = link_to 'Suspend account', suspend_admin_report_path(@report), method: :post, class: 'button'
    %div{ style: 'float: left' }
      = link_to 'Mark as resolved', resolve_admin_report_path(@report), method: :post, class: 'button'
- elsif !@report.action_taken_by_account.nil?
  %hr/

  %p
    %strong Action taken by:
    = @report.action_taken_by_account.acct