config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: 'letter_opener' if Rails.env.development?

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web, at: 'sidekiq', as: :sidekiq
    mount PgHero::Engine, at: 'pghero', as: :pghero
  end

  use_doorkeeper do
    controllers authorizations: 'oauth/authorizations', authorized_applications: 'oauth/authorized_applications'
  end

  get '.well-known/host-meta', to: 'xrd#host_meta', as: :host_meta
  get '.well-known/webfinger', to: 'xrd#webfinger', as: :webfinger

  devise_for :users, path: 'auth', controllers: {
    sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    passwords:          'auth/passwords',
    confirmations:      'auth/confirmations',
  }

  get '/users/:username', to: redirect('/@%{username}'), constraints: { format: :html }

  resources :accounts, path: 'users', only: [:show], param: :username do
    resources :stream_entries, path: 'updates', only: [:show] do
      member do
        get :embed
      end
    end

    get :remote_follow,  to: 'remote_follow#new'
    post :remote_follow, to: 'remote_follow#create'

    member do
      get :followers
      get :following

      post :follow
      post :unfollow
    end
  end

  get '/@:username', to: 'accounts#show', as: :short_account
  get '/@:account_username/:id', to: 'statuses#show', as: :short_account_status

  namespace :settings do
    resource :profile, only: [:show, :update]
    resource :preferences, only: [:show, :update]
    resource :import, only: [:show, :create]

    resource :export, only: [:show] do
      collection do
        get :follows, to: 'exports#download_following_list'
        get :blocks, to: 'exports#download_blocking_list'
      end
    end

    resource :two_factor_auth, only: [:show, :new, :create] do
      member do
        post :disable
      end
    end
  end

  resources :media, only: [:show]
  resources :tags,  only: [:show]

  # Remote follow
  get  :authorize_follow, to: 'authorize_follow#new'
  post :authorize_follow, to: 'authorize_follow#create'

  namespace :admin do
    resources :pubsubhubbub, only: [:index]
    resources :domain_blocks, only: [:index, :new, :create]
    resources :settings, only: [:index, :update]

    resources :reports, only: [:index, :show] do
      member do
        post :resolve
        post :silence
        post :suspend
        post :remove
      end
    end

    resources :accounts, only: [:index, :show] do
      member do
        post :silence
        post :unsilence
        post :suspend
        post :unsuspend
      end
    end
  end

  get '/admin', to: redirect('/admin/settings', status: 302)

  namespace :api do
    # PubSubHubbub outgoing subscriptions
    resources :subscriptions, only: [:show]
    post '/subscriptions/:id', to: 'subscriptions#update'

    # PubSubHubbub incoming subscriptions
    post '/push', to: 'push#update', as: :push

    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    # OEmbed
    get '/oembed', to: 'oembed#show', as: :oembed

    # JSON / REST API
    namespace :v1 do
      resources :statuses, only: [:create, :show, :destroy] do
        member do
          get :context
          get :card
          get :reblogged_by
          get :favourited_by

          post :reblog
          post :unreblog
          post :favourite
          post :unfavourite
        end
      end

      get '/timelines/home',     to: 'timelines#home', as: :home_timeline
      get '/timelines/public',   to: 'timelines#public', as: :public_timeline
      get '/timelines/tag/:id',  to: 'timelines#tag', as: :hashtag_timeline

      get '/search', to: 'search#index', as: :search

      resources :follows,    only: [:create]
      resources :media,      only: [:create]
      resources :apps,       only: [:create]
      resources :blocks,     only: [:index]
      resources :mutes,      only: [:index]
      resources :favourites, only: [:index]
      resources :reports,    only: [:index, :create]

      resource :instance, only: [:show]

      resources :follow_requests, only: [:index] do
        member do
          post :authorize
          post :reject
        end
      end

      resources :notifications, only: [:index, :show] do
        collection do
          post :clear
        end
      end

      resources :accounts, only: [:show] do
        collection do
          get :relationships
          get :verify_credentials
          patch :update_credentials
          get :search
        end

        member do
          get :statuses
          get :followers
          get :following

          post :follow
          post :unfollow
          post :block
          post :unblock
          post :mute
          post :unmute
        end
      end
    end

    namespace :web do
      resource :settings, only: [:update]
    end
  end

  get '/web/(*any)', to: 'home#index', as: :web

  get '/about',      to: 'about#show'
  get '/about/more', to: 'about#more'
  get '/terms',      to: 'about#terms'

  root 'home#index'

  match '*unmatched_route',
    via: :all,
    to: 'application#raise_not_found',
    format: false
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  before_action :set_body_classes
  before_action :set_instance_presenter, only: [:show, :more]

  def show; end

  def more; end

  def terms; end

  private

  def new_user
    User.new.tap(&:build_account)
  end
  helper_method :new_user

  def set_instance_presenter
    @instance_presenter = InstancePresenter.new
  end

  def set_body_classes
    @body_classes = 'about-body'
  end
end

app/views/about/_registration.html.haml
= simple_form_for(new_user, url: user_registration_path) do |f|
  = f.simple_fields_for :account do |account_fields|
    = account_fields.input :username,
      autofocus: true,
      placeholder: t('simple_form.labels.defaults.username'),
      required: true,
      input_html: { 'aria-label' => t('simple_form.labels.defaults.username') }

  = f.input :email,
    placeholder: t('simple_form.labels.defaults.email'),
    required: true,
    input_html: { 'aria-label' => t('simple_form.labels.defaults.email') }
  = f.input :password,
    autocomplete: "off",
    placeholder: t('simple_form.labels.defaults.password'),
    required: true,
    input_html: { 'aria-label' => t('simple_form.labels.defaults.password') }
  = f.input :password_confirmation,
    autocomplete: "off",
    placeholder: t('simple_form.labels.defaults.confirm_password'),
    required: true,
    input_html: { 'aria-label' => t('simple_form.labels.defaults.confirm_password') }

  .actions
    = f.button :button, t('about.get_started'), type: :submit

  .info
    = link_to t('auth.login'), new_user_session_path, class: 'webapp-btn'
    ·
    = link_to t('about.about_this'), about_more_path

app/views/about/more.html.haml
- content_for :page_title do
  #{Rails.configuration.x.local_domain}

.wrapper.thicc
  .sidebar-layout
    .main
      .panel
        %h2= Rails.configuration.x.local_domain

        - unless @instance_presenter.site_description.blank?
          %p= @instance_presenter.site_description.html_safe

      .information-board
        .section
          %span= t 'about.user_count_before'
          %strong= number_with_delimiter @instance_presenter.user_count
          %span= t 'about.user_count_after'
        .section
          %span= t 'about.status_count_before'
          %strong= number_with_delimiter @instance_presenter.status_count
          %span= t 'about.status_count_after'
        .section
          %span= t 'about.domain_count_before'
          %strong= number_with_delimiter @instance_presenter.domain_count
          %span= t 'about.domain_count_after'

      - unless @instance_presenter.site_extended_description.blank?
        .panel= @instance_presenter.site_extended_description.html_safe

    .sidebar
      .panel
        .panel-header= t 'about.contact'
        .panel-body
          - if @instance_presenter.contact_account
            .owner
              .avatar= image_tag @instance_presenter.contact_account.avatar.url
              .name
                = link_to TagManager.instance.url_for(@instance_presenter.contact_account) do
                  %span.display_name.emojify= display_name(@instance_presenter.contact_account)
                  %span.username= "@#{@instance_presenter.contact_account.acct}"

          - unless @instance_presenter.contact_email.blank?
            .contact-email
              = t 'about.business_email'
              %strong= @instance_presenter.contact_email
      .panel
        .panel-header= t 'about.links'
        .panel-list
          %ul
            - if user_signed_in?
              %li= link_to t('about.get_started'), root_path
            - else
              %li= link_to t('about.get_started'), new_user_registration_path
              %li= link_to t('auth.login'), new_user_session_path
            %li= link_to t('about.terms'), terms_path
            %li= link_to t('about.source_code'), 'https://github.com/tootsuite/mastodon'

app/views/about/show.html.haml
- content_for :header_tags do
  = javascript_include_tag 'application_public'

- content_for :page_title do
  = Rails.configuration.x.local_domain

- content_for :header_tags do
  %meta{ property: 'og:site_name', content: site_title }/
  %meta{ property: 'og:type', content: 'website' }/
  %meta{ property: 'og:title', content: Rails.configuration.x.local_domain }/
  %meta{ property: 'og:description', content: strip_tags(@instance_presenter.site_description.blank? ? t('about.about_mastodon') : @instance_presenter.site_description) }/
  %meta{ property: 'og:image', content: asset_url('mastodon_small.jpg') }/
  %meta{ property: 'og:image:width', content: '400' }/
  %meta{ property: 'og:image:height', content: '400' }/
  %meta{ property: 'twitter:card', content: 'summary' }/

.wrapper
  %h1
    = image_tag 'logo.png'
    Mastodon

  %p= t('about.about_mastodon').html_safe

  .screenshot-with-signup
    .mascot= image_tag 'fluffy-elephant-friend.png'

    - if @instance_presenter.open_registrations
      = render 'registration'
    - else
      .closed-registrations-message
        - if @instance_presenter.closed_registrations_message.blank?
          %p= t('about.closed_registrations')
        - else
          = @instance_presenter.closed_registrations_message.html_safe
        .info
          = link_to t('auth.login'), new_user_session_path, class: 'webapp-btn'
          ·
          = link_to t('about.other_instances'), 'https://github.com/tootsuite/mastodon/blob/master/docs/Using-Mastodon/List-of-Mastodon-instances.md'
          ·
          = link_to t('about.about_this'), about_more_path

  %h3= t('about.features_headline')

  .features-list
    .features-list__column
      %ul.fa-ul
        %li
          = fa_icon('li check-square')
          = t 'about.features.chronology'
        %li
          = fa_icon('li check-square')
          = t 'about.features.public'
        %li
          = fa_icon('li check-square')
          = t 'about.features.characters'
        %li
          = fa_icon('li check-square')
          = t 'about.features.gifv'
    .features-list__column
      %ul.fa-ul
        %li
          = fa_icon('li check-square')
          = t 'about.features.privacy'
        %li
          = fa_icon('li check-square')
          = t 'about.features.blocks'
        %li
          = fa_icon('li check-square')
          = t 'about.features.ethics'
        %li
          = fa_icon('li check-square')
          = t 'about.features.api'

  - unless @instance_presenter.site_description.blank?
    %h3= t('about.description_headline', domain: Rails.configuration.x.local_domain)
    %p= @instance_presenter.site_description.html_safe

  .actions
    .info
      = link_to t('about.terms'), terms_path
      ·
      = link_to t('about.apps'), 'https://github.com/tootsuite/mastodon/blob/master/docs/Using-Mastodon/Apps.md'
      ·
      = link_to t('about.source_code'), 'https://github.com/tootsuite/mastodon'
      ·
      = link_to t('about.other_instances'), 'https://github.com/tootsuite/mastodon/blob/master/docs/Using-Mastodon/List-of-Mastodon-instances.md'

app/views/about/terms.en.html.haml
- content_for :page_title do
  #{Rails.configuration.x.local_domain} Terms of Service and Privacy Policy

.wrapper
  %h2 Privacy Policy

  %h3#collect What information do we collect?

  %p We collect information from you when you register on our site and gather data when you participate in the forum by reading, writing, and evaluating the content shared here.

  %p When registering on our site, you may be asked to enter your name and e-mail address. You may, however, visit our site without registering. Your e-mail address will be verified by an email containing a unique link. If that link is visited, we know that you control the e-mail address.

  %p When registered and posting, we record the IP address that the post originated from. We also may retain server logs which include the IP address of every request to our server.

  %h3#use What do we use your information for?

  %p Any of the information we collect from you may be used in one of the following ways:

  %ul
    %li To personalize your experience &mdash; your information helps us to better respond to your individual needs.
    %li To improve our site &mdash; we continually strive to improve our site offerings based on the information and feedback we receive from you.
    %li To improve customer service &mdash; your information helps us to more effectively respond to your customer service requests and support needs.
    %li To send periodic emails &mdash; The email address you provide may be used to send you information, notifications that you request about changes to topics or in response to your user name, respond to inquiries, and/or other requests or questions.

  %h3#protect How do we protect your information?

  %p We implement a variety of security measures to maintain the safety of your personal information when you enter, submit, or access your personal information.

  %h3#data-retention What is your data retention policy?

  %p We will make a good faith effort to:

  %ul
    %li Retain server logs containing the IP address of all requests to this server no more than 90 days.
    %li Retain the IP addresses associated with registered users and their posts no more than 5 years.

  %h3#cookies Do we use cookies?

  %p Yes. Cookies are small files that a site or its service provider transfers to your computer's hard drive through your Web browser (if you allow). These cookies enable the site to recognize your browser and, if you have a registered account, associate it with your registered account.

  %p We use cookies to understand and save your preferences for future visits and compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future. We may contract with third-party service providers to assist us in better understanding our site visitors. These service providers are not permitted to use the information collected on our behalf except to help us conduct and improve our business.

  %h3#disclose Do we disclose any information to outside parties?

  %p We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information. This does not include trusted third parties who assist us in operating our site, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others rights, property, or safety. However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.

  %h3#third-party Third party links

  %p Occasionally, at our discretion, we may include or offer third party products or services on our site. These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.

  %h3#coppa Children's Online Privacy Protection Act Compliance

  %p
    Our site, products and services are all directed to people who are at least 13 years old or older. If this server is in the USA, and you are under the age of 13, per the requirements of COPPA
    = surround '(', '),' do
      = link_to 'Children\'s Online Privacy Protection Act', 'https://en.wikipedia.org/wiki/Children%27s_Online_Privacy_Protection_Act'
    do not use this site.

  %h3#online Online Privacy Policy Only

  %p This online privacy policy applies only to information collected through our site and not to information collected offline.

  %h3#consent Your Consent

  %p By using our site, you consent to our web site privacy policy.

  %h3#changes Changes to our Privacy Policy

  %p If we decide to change our privacy policy, we will post those changes on this page.

  %p This document is CC-BY-SA. It was last updated May 31, 2013.

  %p
    Originally adapted from the
    = succeed '.' do
      = link_to 'Discourse privacy policy', 'https://github.com/discourse/discourse'